### ISSUE TITLE
[1.20.1] Can't load with Java 17

### ISSUE THREAD

**Issue by Deleca7755** [Estecka/mc-Stretchy-Leash#1]
The mod says It's compatible for many versions but with a single jar that force requires Java 21, It will not work on versions below 1.20.5

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
	 - Mod 'Stretchy Leash' (stretchy-leash) 1.0.0+1.20.6 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by Estecka** [comment]
Older versions of Minecraft can run using Java 21, although the specifics on how to achieve that depends on your launcher. Try seeing this with them.

**Comment by Deleca7755** [comment]
Dang It'd seem I'm not a very smart person my bad
![losing it](https://github.com/Estecka/mc-Stretchy-Leash/assets/46870340/74463319-0da1-44fe-9366-4a95a4a7082b)
Ty though!

**Comment by kafkauskas** [comment]
so whats the fix?

**Comment by Deleca7755** [comment]
> so whats the fix?

Google how to change the Java version for the MC launcher you use
https://old.reddit.com/r/feedthebeast/comments/1c9f9gl/way_to_switch_between_versions_of_java/

for me, I use Modrinth:

click gear top right of your Instance
![Image](https://github.com/user-attachments/assets/3ab895f0-76d0-4798-9e0a-3370edba2056)

go to Java and Memory and click Detect
![Image](https://github.com/user-attachments/assets/e15d55e7-812e-4bc9-a4ae-e27c32abaf12)

select any Java 21 version ( make sure to have actually Installed a version of Java 21 )
![Image](https://github.com/user-attachments/assets/ffc2ccd7-2951-4ff7-8f03-d9c996cdbe74)

profit?
![Image](https://github.com/user-attachments/assets/f4f4ebb8-e42c-4bf5-951e-16b83a2991d7)

**Comment by Estecka** [comment]
Fixed in 1.0.1+1.20.1
